autolife/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view

from autolife.local_settings import DEBUG
from content_manager.views import AllAssets,CreateAsset
from autolife.views import index, add_assets, all_assets_list, asset_details, UpdateOrder, edit_asset, clear_cache, \
    version_number, services, jato_cache_clear, GetIP, generate_thumbnail, GenerateClip, easy_insure_cache_clear, \
    gunicorn_restart, nginx_restart, GetImageSource
from core.views import SubscribeMailChimp, MonthlyNewsDigetSubscribeMailChimp

schema_view = get_swagger_view(title='Autolife API Documentation', url="")

urlpatterns = [
    url('^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url('^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^$', index),
    url(r'^get_version', version_number),
    url(r'^generate_clip/$', GenerateClip.as_view()),
    url(r'^get_ip', GetIP.as_view()),
    # url(r'^swagger_api_docs/', schema_view),
    url(r'^get_image_source/', GetImageSource.as_view()),
    url(r'^generate_thumbnail/(?P<asset_id>\d+)/$', generate_thumbnail, name="generate_thumbnail"),
    url(r'^admin/', admin.site.urls),
    url(r'^services/', services, name="3rd_party_services"),
    url(r'^jato_cache/', jato_cache_clear, name="jato_cache_update"),
    url(r'^easy_insure_cache/', easy_insure_cache_clear, name="easy_insure_cache_update"),
    url(r'^restart_gunicorn/', gunicorn_restart, name="restart_gunicorn"),
    url(r'^restart_nginx/', nginx_restart, name="restart_nginx"),
    url(r'^subscribe/$', SubscribeMailChimp.as_view(), name="subscribe"),
    url(r'^monthly_news_digest_subscribe/$', MonthlyNewsDigetSubscribeMailChimp.as_view(), name="monthly news letter subscribe"),
    url(r'^admin/add_assets/$', add_assets, name="assets_url"),
    url(r'^admin/edit_assets/(?P<asset_id>\d+)/$', edit_asset, name="edit_assets"),
    url(r'^admin/update_order/(?P<asset_id>\d+)/$', UpdateOrder.as_view(), name="update_order"),
    url(r'^admin/all_assets/$', all_assets_list, name="all_assets"),
    url(r'^admin/asset_detail/(?P<asset_id>\d+)$', asset_details, name="asset_details"),
    url(r'^clear_cache/$', clear_cache, name="clear_cache"),
    url(r'^services/$', services, name="services"),
    url(r'^soft_registration/', include('questionnaire.urls')),
    url(r'^analytics/', include('analytics.urls')),
    url(r'^marketplace/', include('marketplace.urls', namespace="marketplace")),
    url(r'^oauth2_provider/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # needed for Oauth URL check
    url(r'^auth/', include('rest_framework_social_oauth2.urls')),  # Never ever change this to somewhere else
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^content_manager/', include('content_manager.urls', namespace="content management")),
    url(r'^soft_registration/', include('questionnaire.urls', namespace="questionnaire")),
    url(r'^tags/', include('tags.urls', namespace="tags")),
    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^assets/all/', AllAssets.as_view(), name="list-all-assets"),
    url(r'^assets/create/', CreateAsset.as_view(), name="create-assets"),
    url(r'^ui_controllers/', include('ui_controllers.urls', namespace="ui_controls")),
    url(r'^recall/', include('vehicles.urls', namespace="recall")),
    # Add assets

]

if DEBUG:
    urlpatterns += [
        url(r'^drf_api_docs/', include_docs_urls(title="Autolife Api Docs", authentication_classes=[],
                                                 permission_classes=[])),
    ]

tags/urls.py
from django.conf.urls import url

from tags.views import LifestyleAPI

urlpatterns = [
    url(r'^lifestyle/', LifestyleAPI.as_view(), name='lifestyle'),
]

ui_controllers/urls.py
from django.conf.urls import url

from ui_controllers.views import template_list, UpdateOrder, UITiles, UITiles2, OtherTiles, PollVote, AllCategories, \
    CreateTile, UpdateTile, DeleteTile, SetTileOrder, UnusedTiles, FetchTiles

urlpatterns = [
	url(r'^tiles/', template_list, name='tiles_list'),
	url(r'^update/', UpdateOrder.as_view(), name='tile_ordering'),
	url(r'^polls/(?P<answer_id>\w+)/$', PollVote.as_view(), name='poll_vote'),

	# API UI tiles
	url(r'^homepage_default_tiles/', UITiles.as_view(), name='homepage_default_tiles'),
    url(r'^new_homepage_default_tiles/', UITiles2.as_view(), name='new_homepage_default_tiles'),
    url(r'^all_categories/', AllCategories.as_view(), name='all_categories'),
    url(r'^create_tile/', CreateTile.as_view(), name='create_tile'),
    url(r'^update_tile/(?P<tile_id>\w+)/', UpdateTile.as_view(), name='update_tile'),
    url(r'^delete_tile/(?P<tile_id>\w+)/', DeleteTile.as_view(), name='delete_tile'),
    url(r'^set_tiles_order/', SetTileOrder.as_view(), name='set_tiles_order'),
    url(r'^unused_tiles/', UnusedTiles.as_view(), name='unused_tiles'),
    url(r'^fetch_tiles/', FetchTiles.as_view(), name='fetch_tiles_based_on_category'),
	url(r'^(?P<tile_category>\w+)/', OtherTiles.as_view(), name='other_ui_tiles'),

]

ui_controllers/views.py
import json

from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render

# Create your views here.
from django.template.context_processors import csrf
from rest_framework import generics, status
from rest_framework.permissions import AllowAny, IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from content_manager.utilities.news_utils import NewsListing
from content_manager.utilities.cms_utils import IsSuperUser
from library.al_lib import ALResponse
from marketplace.utility.polls import Polls
from ui_controllers.models import ControllerTile, ControllerCategory, HOME_1, HOME_2, FEATURED_HOME_1, FEATURED_HOME_2
from ui_controllers.serializers import UiTilesSerializer, RecentArticleSerializer
from ui_controllers.utility.utils import ArticleMightLike, OtherCategoryListing, ArticleRecent, OtherCategoryListing2, \
	NewArticleRecent, CreateUpdateTile


@user_passes_test(lambda u: u.is_superuser)
def template_list(request):
	categorized_tiles = []
	for category in ControllerCategory.objects.all():
		obj = {
			"name": category.category_name,
			"id": category.id,
			"tiles": ControllerTile.objects.filter(category_id=category.id).order_by("order")
		}
		categorized_tiles.append(obj)
	context = {"tiles": categorized_tiles}
	context.update(csrf(request))
	return render(request, "order_tiles.html", context)


class UpdateOrder(APIView):
	"""
	Updates Tile order
	ui_tile_order : required
	"""
	permission_classes = ()
	authentication_classes = ()

	def post(self, request):
		if request.unauthorized:
			return Response(data={"message": "Unauthorized"},  status=401)
		order = request.data.get("ui_tile_order")
		try:
			for each_order in order:
				tile = ControllerTile.objects.get(id=int(each_order))
				tile.order = order.index(each_order)
				tile.save()
			return Response(data={"message": "order updated"}, status=200)
		except Exception as e:
			return Response(data={"message": "error"}, status=404)


class UITiles(APIView):
	"""
	Homepage Default Tile Listing API.
	This API will list all Homepage tiles. Called First on Homepage load and after Login
	"""
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (AllowAny,)

	def get(self, request):
		data = {}
		print(request.user)
		if not request.user.is_authenticated:
			data["others"] = ControllerCategory.objects.category_tiles(HOME_1)
			try:
				data["featured"] = ControllerCategory.objects.category_tiles(FEATURED_HOME_1)
			except ControllerCategory.DoesNotExist:
				data["featured"] = []
		else:
			default_tiles = ControllerCategory.objects.category_tiles(HOME_2)
			# data_obj = ArticleMightLike(user=request.user)
			data_obj = ArticleRecent(user=request.user)
			user_related = data_obj.parse()
			user_related += default_tiles
			data["others"] = user_related

			try:
				data["featured"] = ControllerCategory.objects.category_tiles(FEATURED_HOME_2)
			except ControllerCategory.DoesNotExist:
				data["featured"] = []
		return ALResponse(
			data=data, status=200, message="OK"
		).success()



class UITiles2(generics.ListAPIView):
	"""
	Optimized Homepage Default Tile Listing API.
	This API will list all Homepage tiles. Called First on Homepage load and after Login
	"""
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (AllowAny,)
	serializer_class = UiTilesSerializer

	def get_queryset(self):
		return NewArticleRecent().homepage_queryset(self.param)

	def list(self, request, *args, **kwargs):
		self.param = HOME_1


		if request.user.is_authenticated:
			self.param = HOME_2
			recent_articles_queryset = NewArticleRecent().recent_articles_queryset()
			recent_serializer_data = RecentArticleSerializer(recent_articles_queryset, many=True)
			queryset = self.filter_queryset(self.get_queryset())
			serializer = self.get_serializer(queryset, many=True)

			# For Featured
			featured_queryset = NewArticleRecent().homepage_queryset(FEATURED_HOME_2)
			featured_serializer_data = UiTilesSerializer(featured_queryset, many=True)


		else:
			recent_serializer_data = None
			queryset = self.filter_queryset(self.get_queryset())
			serializer = self.get_serializer(queryset, many=True)

			# For Featured
			featured_queryset = NewArticleRecent().homepage_queryset(FEATURED_HOME_1)
			featured_serializer_data = UiTilesSerializer(featured_queryset, many=True)


		serialized_data = {}
		if recent_serializer_data:
			serialized_data['others'] = recent_serializer_data.data + serializer.data
		else:
			serialized_data["others"] = serializer.data

		serialized_data['featured'] = featured_serializer_data.data

		return ALResponse(data=serialized_data, status=200, message="OK").success()


class OtherTiles(APIView):
	"""
	Marketplace and Insurance tiles
	"""
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (AllowAny,)

	def get(self, request, tile_category):
		tile_category=tile_category.lower()

		if request.user.is_authenticated:
			data = OtherCategoryListing(tile_category)
			return ALResponse(
				data=data, status=200, message="OK"
			).success()

		else:
			data = OtherCategoryListing2(tile_category)
			return ALResponse(
				data=data, status=200, message="OK"
			).success()


class PollVote(APIView):
	"""
	Vote methods for
	"""
	authentication_classes = ()
	permission_classes = ()

	def post(self, request, answer_id):
		return ALResponse(data=Polls().vote_method(answer_code=answer_id,
												   email=request.data.get("email").lower(),
												   poll_id=request.data.get("poll_id")
												   ),
						  status=200).success()




class AllCategories(APIView):
	"""
	Fetch all tiles categories
	"""
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def get(self, request, ):
		data = ControllerCategory.objects.all()
		result =[category.to_json for category in data]
		return ALResponse(data=result,status=200).success()



class CreateTile(APIView):
	"""
    Api to create tile
    """
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def post(self,request):

		create_tile =CreateUpdateTile(request.data,request.user)

		return Response(data=create_tile,status=status.HTTP_200_OK)

class UpdateTile(APIView):
	"""
    Api to create tile
    """
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def post(self,request,tile_id):

		try:
			tileobj =ControllerTile.objects.get(id=tile_id)
		except:
			tileobj = None
		if tileobj:
			update_tile = CreateUpdateTile(request.data, request.user, tile_id=tile_id)
			return Response(data=update_tile, status=status.HTTP_200_OK)
		else:
			return Response(data={"Message": "Tile Not found"}, status=status.HTTP_400_BAD_REQUEST)




class DeleteTile(APIView):
	"""
    Api to create tile
    """
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def post(self,request,tile_id):

		try:
			tileobj =ControllerTile.objects.get(id=tile_id)
		except:
			tileobj = None
		if tileobj:
			tileobj.delete()
			return Response(data={"Message":"Tile deleted succesfully"}, status=status.HTTP_200_OK)
		else:
			return Response(data={"Message": "Tile Not found"}, status=status.HTTP_400_BAD_REQUEST)



class SetTileOrder(APIView):
	"""
    Set order of tile
    """
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def post(self,request):

		category = request.data.get("category")
		categoryobj =ControllerCategory.objects.get(id=category)
		tiles = ControllerTile.objects.filter(category__id=category)
		tiles.update(category=None)

		tiles =request.data.get('tiles')
		#
		for tile in range(len(tiles)):
			tileobj =ControllerTile.objects.get(id=tiles[tile])
			tileobj.order =tile
			tileobj.category =categoryobj
			tileobj.is_active = True
			tileobj.save()
		return Response(data={"Message": "Tile order and category has been updated"}, status=status.HTTP_200_OK)


class UnusedTiles(APIView):
	"""
    Api to fetch unused tiles
    """

	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def get(self, request):
		data = ControllerTile.objects.filter(category__isnull=True) | ControllerTile.objects.filter (is_active=False).order_by('-updated_on')
		if data:
			return Response(data=[tiles.to_json for tiles in data], status=status.HTTP_200_OK)
		else:
			return Response(data=[], status=status.HTTP_200_OK)

class FetchTiles(APIView):
	"""
    Api to fetch tiles as per category
    """
	authentication_classes = (JSONWebTokenAuthentication,)
	permission_classes = (IsAdminUser,)

	def post(self, request, ):
		category = request.data.get("category",None)
		queryset =ControllerTile.objects.filter(category__id=category).order_by('order')
		return Response(data=[tiles.to_json for tiles in queryset],status=status.HTTP_200_OK)

ui_controllers/templates/order_tiles.html
{% extends "admin/base_site.html" %}
{% block title %}Order Tiles{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumb">
    <li style="list-style: None;"><a href="/admin/">Home</a>
        <span class="divider">»</span></li>
    <li style="list-style: None;"><a href="/admin/ui_controllers/">UI Controllers</a>
        <span class="divider">»</span></li>
    <li style="list-style: None;">Ordering Tiles
        <span class="divider">»</span></li>
    </div>
{% endblock %}
{% block content %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <div class="muted">
        Drag and drop table rows to set the order.<br/>
    </div>
    {% for category_tiles in tiles %}
        <h2 class="text-info text-center">{{ category_tiles.name | title }}</h2>
        <table id="result_list" class="table table-striped table-bordered table-hover table-condensed">
            <thead>
            <tr>


                <th scope="col" class="id-column sortable column-id">


                    <div class="text">
                        <a href="#">ID</a>
                    </div>
                </th>
                <th scope="col" class="name-column sortable column-name">


                    <div class="text">
                        <a href="#">Name</a>
                    </div>
                </th>
                <th scope="col" class="name-column sortable column-name">


                    <div class="text">
                        <a href="#">Category</a>
                    </div>
                </th>
                <th scope="col" class="name-column sortable column-name">


                    <div class="text">
                        <a href="#">Status</a>
                    </div>
                </th>
            </tr>
            </thead>
            <tbody id="sortable{{ category_tiles.id }}">

            {% for tile in category_tiles.tiles %}

                <tr class="row1" id="{{ tile.id }}">

                    <th class="field-id"><a
                            href="/admin/ui_controllers/controllertile/{{ tile.id }}/change/">{{ tile.id }}</a></th>
                    <td class="field-name">{{ tile.tile_name }}
                    </td>
                    <td class="field-name">{{ category_tiles.name | title }}
                    </td>
                    <td class="field-name">{% if tile.is_active %} Active {% else %} Preview {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button class="pull-right btn btn-info" id="update-order{{ category_tiles.id }}">Set Order</button><br/>
        <script>
            $( function() {
                $( "#sortable{{ category_tiles.id }}" ).sortable();
                $("#update-order"+'{{ category_tiles.id }}').click(function (evt) {
                    var childs =  $("#sortable{{ category_tiles.id }}").children();
                    var results = [];
                    for(i=0; i<childs.length; i++){
                        div_id = $(childs[i]).attr("id");
                        results.push(div_id);
                    }
                    console.log(results);
                    var url = '{% url "ui_controls:tile_ordering" %}';
                    $.ajax({
                        url: url,
                        type: "POST",
                        data: JSON.stringify({'ui_tile_order': results}),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (response) {
                            alert(response.message);
                        }
                    })

                })
            } );
        </script>

    {% endfor %}
{% endblock %}